import type { Metadata } from "next"
import Header from './components/header'
import Footer from "./components/footer"
import MouseGradient from "./components/mouse"
import "./globals.css"

export const metadata: Metadata = {
  title: "Raegen Ellis",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children }: Readonly<{children: React.ReactNode}>) 
{
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <MouseGradient />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
