import type { Metadata } from "next";
import Header from './components/header'
import Footer from "./components/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Raegen Ellis",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children}: Readonly<{children: React.ReactNode}>) 
{
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
